### ISSUE TITLE
Hope to play with soundfont

### ISSUE THREAD

**Issue by maxdanielc** [Wohlstand/OPNMIDI-Player-Java#2]
I hope to play on a different sound.
so how can I set the soundfont in this project

**Comment by Wohlstand** [comment]
Did you meant to use a custom bank? Note that for FM synth the "soundfont" term is not applayable because of a different logic of sounf generation. You need to load to your phone some set of WOPN files: each file defines an instruments bank that defines the sounding. Use the "Open custom bank" button to choose any WOPN file on your phone and check the "use custom bank" flag to toggle using of your bank, or uncheck to use dedault.

You can find sample WOPN banks you can try here in the "fm_banks" folder: https://github.com/Wohlstand/libOPNMIDI

Also you can edit them or even make your own banks yourself (you can even import instruments from VGM files you like): https://github.com/Wohlstand/OPN2-Bank-Editor

**Comment by Wohlstand** [comment]
BTW, unlike wavetable synthesizers, banks are much smaller because to define the sound, you should tweak and tune parameters of timbre operators are used in a formula that is used to compute a sound you'll hear in final.

**Comment by maxdanielc** [comment]
thanks for your reply.

**Comment by maxdanielc** [comment]
I make the decision to use synth banks. but I can't access https://github.com/Wohlstand/OPN2-Bank-Editor

**Comment by Wohlstand** [comment]
Oh, damb, sorry, I have incorrectly typed a path to the editor from a phone

**Comment by Wohlstand** [comment]
https://github.com/Wohlstand/OPN2BankEditor

**Comment by maxdanielc** [comment]
Really thanks for your clear answers.
